-- V001__control_plane.sql
-- KLIBRA control plane — TDD §39, ADR-001, Constitution §VII.
-- Operational metadata only. Historical analytical data lives in
-- Raw / Bronze / Silver / Gold in object storage (TDD §6, ADR-001).
--
-- This migration is intentionally append-only. New control-plane tables
-- land in V002__...sql; do not edit this file once released.

BEGIN;

-- ── Roles & access —──────────────────────────────
CREATE ROLE klibra_app LOGIN PASSWORD 'CHANGE_ME';
CREATE ROLE klibra_airflow LOGIN PASSWORD 'CHANGE_ME';
CREATE ROLE klibra_analyst LOGIN PASSWORD 'CHANGE_ME';
CREATE ROLE klibra_auditor LOGIN PASSWORD 'CHANGE_ME';

GRANT CONNECT ON DATABASE klibra TO klibra_app, klibra_airflow, klibra_analyst, klibra_auditor;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO klibra_analyst;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO klibra_auditor;

-- ── Source registry — single row per approved source ───
CREATE TABLE source_registry (
    source_id           TEXT PRIMARY KEY,
    provider            TEXT NOT NULL,
    dataset             TEXT NOT NULL,
    access_class        CHAR(1) NOT NULL CHECK (access_class IN ('A', 'B', 'C')),
    auth_model          TEXT NOT NULL,
    endpoint            TEXT NOT NULL,
    auth_env            TEXT,
    rate_limit_rpm      INTEGER,
    terms_url           TEXT,
    historical_coverage DATE,
    update_cadence      TEXT NOT NULL,
    revision_behavior   TEXT NOT NULL,
    contract_stability  TEXT NOT NULL,
    last_verified_date  DATE NOT NULL,
    fallback_strategy   TEXT,
    live_request_verified BOOLEAN NOT NULL DEFAULT FALSE,
    owner_email         TEXT NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_source_registry_access_class ON source_registry (access_class);
CREATE INDEX idx_source_registry_live ON source_registry (live_request_verified);

-- ── Dataset registry — one row per logical dataset ─────
CREATE TABLE dataset_registry (
    dataset_id          TEXT PRIMARY KEY,
    source_id           TEXT NOT NULL REFERENCES source_registry (source_id),
    description         TEXT,
    schema_version      TEXT NOT NULL DEFAULT 'v1',
    freshness_hours     INTEGER,
    quality_threshold_id TEXT,
    classification      TEXT NOT NULL DEFAULT 'INTERNAL',
    owner_email         TEXT NOT NULL,
    deprecated         BOOLEAN NOT NULL DEFAULT FALSE,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_dataset_registry_source ON dataset_registry (source_id);

-- ── Run history — one row per pipeline run ────────────
CREATE TABLE run_history (
    run_id              UUID PRIMARY KEY,
    pipeline_id         TEXT NOT NULL,
    dataset_id          TEXT NOT NULL REFERENCES dataset_registry (dataset_id),
    source_id           TEXT NOT NULL REFERENCES source_registry (source_id),
    started_at          TIMESTAMPTZ NOT NULL,
    completed_at        TIMESTAMPTZ,
    status              TEXT NOT NULL CHECK (
        status IN ('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', 'QUARANTINED')
    ),
    records_received    INTEGER,
    records_written     INTEGER,
    records_rejected    INTEGER,
    payload_hash        TEXT,
    source_version      TEXT,
    max_observation_date DATE,
    min_observation_date DATE,
    schema_version      TEXT,
    error_type          TEXT,
    error_message       TEXT
);

CREATE INDEX idx_run_history_dataset ON run_history (dataset_id, started_at DESC);
CREATE INDEX idx_run_history_status ON run_history (status, started_at DESC);

-- ── Metric registry — semantic + intelligence products ──
CREATE TABLE metric_registry (
    metric_id           TEXT NOT NULL,
    version             TEXT NOT NULL,
    is_intelligence     BOOLEAN NOT NULL DEFAULT FALSE,
    display_name        TEXT NOT NULL,
    description         TEXT NOT NULL,
    owner_email         TEXT NOT NULL,
    grain               JSONB NOT NULL,
    unit                TEXT,
    formula             TEXT,
    source_policy       JSONB NOT NULL,
    aggregation_policy  TEXT NOT NULL CHECK (
        aggregation_policy IN ('ADDITIVE', 'AVERAGING', 'END_OF_PERIOD',
                                'LATEST_OBSERVATION', 'WEIGHTED', 'NON_AGGREGATABLE')
    ),
    time_semantics      TEXT NOT NULL,
    quality_requirements JSONB,
    lineage_ref         TEXT,
    effective_from      DATE NOT NULL,
    deprecation_status  TEXT NOT NULL CHECK (
        deprecation_status IN ('ACTIVE', 'DEPRECATED', 'RETIRED')
    ),
    PRIMARY KEY (metric_id, version)
);

CREATE INDEX idx_metric_registry_active ON metric_registry (metric_id) WHERE deprecation_status = 'ACTIVE';

-- ── Ownership registry — three-owner model ───────────
CREATE TABLE ownership_registry (
    asset_id            TEXT NOT NULL,
    asset_type          TEXT NOT NULL CHECK (asset_type IN ('dataset', 'metric', 'source', 'intelligence')),
    business_owner      TEXT NOT NULL,
    data_owner          TEXT NOT NULL,
    technical_owner     TEXT NOT NULL,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (asset_id, asset_type)
);

-- ── Incident log — P0/P1/P2/P3 incidents ───────────────
CREATE TABLE incident_log (
    incident_id         TEXT PRIMARY KEY,
    started_at          TIMESTAMPTZ NOT NULL,
    detected_at         TIMESTAMPTZ NOT NULL,
    resolved_at         TIMESTAMPTZ,
    affected_dataset    TEXT,
    severity            TEXT NOT NULL CHECK (severity IN ('P0', 'P1', 'P2', 'P3')),
    impact              TEXT NOT NULL,
    root_cause          TEXT,
    resolution          TEXT,
    recovery_actions    TEXT,
    preventive_actions  TEXT,
    owner_email         TEXT NOT NULL
);

CREATE INDEX idx_incident_log_severity ON incident_log (severity, started_at DESC);
CREATE INDEX idx_incident_log_dataset ON incident_log (affected_dataset);

-- ── Lineage — per-run lineage records (TDD §69) ────────
CREATE TABLE lineage (
    lineage_id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    run_id              UUID NOT NULL REFERENCES run_history (run_id),
    connector_version    TEXT,
    transformation_version TEXT,
    source_payload_hash TEXT,
    semantic_metric_version TEXT,
    intelligence_methodology_version TEXT,
    input_snapshot_id   UUID,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_lineage_run ON lineage (run_id);

-- ── Schema versioning audit (TDD §19, §67) ─────────────
CREATE TABLE schema_fingerprint (
    fingerprint_id      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    source_id           TEXT NOT NULL REFERENCES source_registry (source_id),
    dataset_id          TEXT NOT NULL REFERENCES dataset_registry (dataset_id),
    payload_hash        TEXT NOT NULL,
    schema_json         JSONB NOT NULL,
    change_class        TEXT NOT NULL CHECK (
        change_class IN ('COMPATIBLE', 'POTENTIALLY_BREAKING', 'BREAKING')
    ),
    detected_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (source_id, dataset_id, payload_hash)
);

-- ── Trigger: keep updated_at fresh ───────────────────
CREATE OR REPLACE FUNCTION klibra_set_updated_at() RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER source_registry_set_updated_at BEFORE UPDATE ON source_registry
    FOR EACH ROW EXECUTE FUNCTION klibra_set_updated_at();
CREATE TRIGGER dataset_registry_set_updated_at BEFORE UPDATE ON dataset_registry
    FOR EACH ROW EXECUTE FUNCTION klibra_set_updated_at();

COMMIT;
